# Generated by Django 4.2.11 on 2024-03-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='location_image',
        ),
    ]
