# Generated by Django 4.2.11 on 2024-03-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_latitude_attendance_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='location',
        ),
    ]
