# Generated by Django 4.2.11 on 2024-03-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_attendance_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
