# Generated by Django 4.2.11 on 2024-03-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='longitude',
        ),
    ]
